const fs=require('fs'),vm=require('vm'),assert=require('assert');
let saved=null,html='',handlers={},context,timers=[];
const data=fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/ch02-data.js','utf8'),app=fs.readFileSync('dist/app.js','utf8');
function boot(){handlers={};timers=[];const root={set innerHTML(s){html=s},get innerHTML(){return html}};const document={querySelector:s=>s==='#app'?root:null,querySelectorAll:()=>[],addEventListener:(e,f)=>handlers[e]=f,createElement:()=>({setAttribute(){},remove(){}}),body:{append(){}}};context=vm.createContext({document,localStorage:{getItem:()=>saved,setItem:(k,s)=>saved=s},window:{scrollTo(){}},navigator:{},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},Date});vm.runInContext(data+app,context)}
const click=dataset=>{vm.runInContext('inputLockedUntil=0',context);handlers.click({target:{closest:()=>({dataset,disabled:false})}})},action=x=>click({action:x}),nav=x=>click({nav:x}),selectChoice=i=>click({choice:String(i)}),answer=i=>click({answer:String(i)});
const current=()=>JSON.parse(saved),story=()=>current().run.storyId;
function reveal(){let n=0;while(html.includes('data-action="advance-dialogue"')){action('advance-dialogue');if(++n>15)throw Error('dialogue guard')}}
function next(){reveal();action('next')}function choose(i){reveal();selectChoice(i);reveal();action('result-next')}
function answerAndContinue(i){answer(i);assert(html.includes(i===vm.runInContext(`QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer`,context)?'기억이 선명해졌다':'기억이 흐릿하다'));action('quiz-next')}

boot();
vm.runInContext("state.run.started=true;state.run.stats={health:88,knowledge:11,fame:6,wealth:24};state.run.relations.doyun=19;state.run.job='상단 장부 보조';state.run.route='merchant';finishChapter(state);save();",context);
nav('teaser');assert(html.includes('CHAPTER 02 · UNLOCKED'));action('start-ch02');
assert.equal(current().run.currentChapter,'ch02');assert.equal(story(),'ch02_transition');assert.equal(current().run.stats.wealth,24);assert.equal(current().run.job,'상단 장부 보조');assert(html.includes('CH.02'));
assert.equal(current().run.playerOutfit,'goryeo_commoner');assert.equal(current().run.flags.wearingModernClothes,false);next();assert.equal(story(),'ch02_market');reveal();assert(html.includes('data-speaker-type="thought"'));assert(html.includes('player_goryeo_thinking'));assert(vm.runInContext("STORIES.ch02_market.dialogues.some(line=>line.speakerType==='npc')",context));choose(0);assert.equal(current().meta.knowledgeMemory['ch02-king-after-taejo'].answer,'광종');
assert.equal(story(),'ch02_life_path');choose(0);assert.equal(current().run.lifePath,'doyun-merchant-partner');assert(current().run.sharedEvents.includes('helped_doyun_business'));
assert.equal(story(),'ch02_dispute');reveal();assert(html.includes('message-row npc'));assert(vm.runInContext("STORIES.ch02_dispute.dialogues.some(line=>line.speakerType==='player'&&line.alignment==='right')",context));next();assert.equal(story(),'ch02_trust');choose(0);assert.equal(current().run.relations.citizens,3);assert.equal(current().run.trust.doyun,9);assert(current().run.sharedEvents.includes('helped_doyun_friend'));
assert.equal(story(),'ch02_inspection');next();assert.equal(story(),'ch02_policy_reason');choose(0);assert(current().run.flags.understandsNobi);assert.equal(current().meta.knowledgeMemory['ch02-nobi-purpose'].correct,true);
assert.equal(story(),'ch02_policy_memory');next();assert.equal(current().run.activeQuestionId,'ch02-test-01');answerAndContinue(0);assert(current().meta.wrongQuestionIds.includes('ch02-test-01'));
assert.equal(story(),'ch02_noble_night');next();assert.equal(story(),'ch02_exam_notice');reveal();assert(html.includes('hyunwoo_neutral'));next();assert.equal(story(),'ch02_three_way');reveal();assert(html.includes('둘이 벌써 친해졌네'));next();assert.equal(story(),'ch02_ssanggi');next();answerAndContinue(0);
assert.equal(story(),'ch02_exam_eve');reveal();assert(html.includes('현우에게 무슨 말을'));choose(0);assert.equal(current().run.relations.hyunwoo,5);assert.equal(current().run.trust.hyunwoo,5);assert(current().run.sharedEvents.includes('supported_hyunwoo_exam'));
assert.equal(story(),'ch02_exam_day');next();assert.equal(story(),'ch02_reign_titles');next();answerAndContinue(1);assert.equal(story(),'ch02_reign_followup');next();answerAndContinue(4);assert.equal(story(),'ch02_purge');assert(!html.includes('알 수 없는 기억'));assert(!current().meta.mysteries.includes('unknown-aging'));reveal();assert(html.includes('data-speaker-type="thought"'));action('next');answerAndContinue(0);
assert(current().run.completed);assert.equal(story(),'ch02_complete');assert(html.includes('CHAPTER 02 COMPLETE'));assert(html.includes('노비안검법'));assert(html.includes('과거제'));assert(html.includes('광덕 · 준풍'));assert(current().meta.completedChapters.includes('ch01'));assert(current().meta.completedChapters.includes('ch02'));
nav('teaser');assert(html.includes('CHAPTER 03 · NEXT'));assert(html.includes('시무 28조'));
nav('complete');action('request-replay');assert(html.includes('CH.02을 다시 플레이할까요?'));assert(html.includes('이미 완료한 이후 챕터의 진행 기록은 유지됩니다.'));click({action:'confirm-replay',chapter:'ch02'});assert.equal(current().run.mode,'replay');assert.equal(current().run.currentChapter,'ch02');assert.equal(story(),'ch02_transition');assert.equal(current().run.stats.wealth,24);assert.equal(current().run.job,'상단 장부 보조');assert.equal(current().run.relations.doyun,19);assert.equal(current().run.choices.length,0);assert(current().meta.completedChapters.includes('ch01'));assert(current().meta.completedChapters.includes('ch02'));
boot();action('play');assert.equal(current().run.currentChapter,'ch02');assert.equal(story(),'ch02_transition');
console.log('PASS: CH.02 carry-over, character arcs, five choice points, period voice, five story tests, mystery removal, wrong-note save, completion, CH.03 teaser, reload, and replay start.');
