const fs=require('fs'),vm=require('vm'),assert=require('assert');
let saved=null,html='',handlers={},context,timers=[];
const data=fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/ch02-data.js','utf8')+'\n'+fs.readFileSync('dist/ch03-data.js','utf8')+'\n'+fs.readFileSync('dist/exam-data.js','utf8')+'\n'+fs.readFileSync('dist/ch01-expansion.js','utf8')+'\n'+fs.readFileSync('dist/chapter-split.js','utf8')+'\n'+fs.readFileSync('dist/late-goryeo.js','utf8')+'\n'+fs.readFileSync('dist/official-late-exams.js','utf8'),app=fs.readFileSync('dist/app.js','utf8');
function boot(){handlers={};timers=[];const root={set innerHTML(s){html=s},get innerHTML(){return html}};const document={querySelector:s=>s==='#app'?root:null,querySelectorAll:()=>[],addEventListener:(e,f)=>handlers[e]=f,createElement:()=>({setAttribute(){},remove(){}}),body:{append(){}}};context=vm.createContext({document,localStorage:{getItem:()=>saved,setItem:(k,s)=>saved=s},window:{scrollTo(){}},navigator:{},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},Date});vm.runInContext(data+app,context)}
const click=dataset=>{vm.runInContext('inputLockedUntil=0',context);handlers.click({target:{closest:()=>({dataset,disabled:false})}})},action=x=>click({action:x}),nav=x=>click({nav:x}),selectChoice=i=>click({choice:String(i)}),answer=i=>click({answer:String(i)});
const current=()=>JSON.parse(saved),story=()=>current().run.storyId;
function reveal(){let n=0;while(html.includes('data-action="advance-dialogue"')){action('advance-dialogue');if(++n>15)throw Error('dialogue guard')}}
const addedQueues={"ch03-early-kings":["ch03-pdf-69-advanced-10","ch03-pdf-75-basic-12"],"ch03-policy-comparison":["ch03-pdf-65-advanced-10"],"ch03-centralization":["ch03-pdf-65-advanced-11"],"ch03-official-education":["ch03-pdf-76-advanced-11"],"ch03-royal-policy-check":["ch03-pdf-70-advanced-13","ch03-pdf-79-advanced-13"],"ch03-kingdom-system-check":["ch03-pdf-72-advanced-11"]};
function drainAddedQuestions(){while(current().run.activeQuestionId&&addedQueues[current().run.activeQuestionSetId])drainSceneQuestions(addedQueues[current().run.activeQuestionSetId]);}
function next(){reveal();action('next');drainAddedQuestions()}function choose(i){reveal();selectChoice(i);reveal();action('result-next');drainAddedQuestions()}
function drainSupplementalQuestions(){let guard=0;while(vm.runInContext(`Boolean(STORIES[${JSON.stringify(story())}]?.supplementalExam)`,context)){next();const correct=vm.runInContext('QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer',context);answer(correct);assert(html.includes('기억이 선명해졌다'));action('quiz-next');if(++guard>8)throw new Error('supplemental quiz guard')}}
function answerAndContinue(i){answer(i);assert(html.includes(i===vm.runInContext(`QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer`,context)?'기억이 선명해졌다':'기억이 흐릿하다'));action('quiz-next');drainSupplementalQuestions()}

function drainSceneQuestions(expected){let ids=[];while(current().run.activeQuestionId){const q=vm.runInContext('QUESTIONS.find(q=>q.questionId===run().activeQuestionId)',context);ids.push(q.questionId);assert(html.includes(q.isOfficial?'제'+q.examRound+'회':'[심화 연습]'));assert(html.includes(q.question));q.choices.forEach((_,i)=>assert(html.includes('data-answer="'+i+'"')));answerAndContinue(q.answer)}assert.deepEqual(ids,expected)}
boot();
vm.runInContext("state.run.started=true;state.run.stats={health:88,knowledge:11,fame:6,wealth:24};state.run.relations.doyun=19;state.run.job='상단 장부 보조';state.run.route='merchant';finishChapter(state);if(state.run.currentChapter==='ch01'){startChapter(state,'ch02');finishChapter(state);}save();",context);
nav('teaser');assert(html.includes('CHAPTER 03 · UNLOCKED'));click({action:'start-chapter',chapter:'ch03'});
assert.equal(current().run.currentChapter,'ch03');assert.equal(story(),'ch02_transition');assert.equal(current().run.stats.wealth,24);assert.equal(current().run.job,'상단 장부 보조');assert(html.includes('CH.03'));
assert.equal(current().run.playerOutfit,'goryeo_commoner');assert.equal(current().run.flags.wearingModernClothes,false);assert.equal(current().run.characterStates.doyun.ageVariant,'middle_aged_949');assert.equal(current().run.characterStates.doyun.characterAge,55);assert(vm.runInContext("STORIES.ch02_transition.dialogues.map(x=>x.dialogue).join('|').includes('918년 — 고려 건국')&&STORIES.ch02_transition.dialogues.map(x=>x.dialogue).join('|').includes('949년 — 개경')",context));
next();assert.equal(story(),'ch02_shop_exterior_949');assert(html.includes('ch02-doyun-shop-exterior-949'));next();assert.equal(story(),'ch02_reunion_949');reveal();assert(!html.includes('character-stage'));assert(html.includes('data-speaker-type="thought"'));next();assert.equal(story(),'ch02_market');reveal();assert(!html.includes('character-stage'));assert(vm.runInContext("STORIES.ch02_market.dialogues.some(line=>line.speakerType==='npc')",context));choose(0);assert.equal(current().meta.knowledgeMemory['ch02-king-after-taejo'].answer,'광종');
drainSceneQuestions(['ch03-practice-king-949','ch03-practice-kings-flow']);assert.equal(story(),'ch02_life_path');choose(0);assert.equal(current().run.lifePath,'doyun-merchant-partner');assert(current().run.sharedEvents.includes('helped_doyun_business'));assert.equal(story(),'ch02_jump_956');next();drainSceneQuestions(['ch03-practice-king-956']);assert.equal(story(),'ch02_shop_956');assert.equal(current().run.characterStates.doyun.ageVariant,'elder_956');assert.equal(current().run.characterStates.doyun.characterAge,62);reveal();assert(!html.includes('character-stage'));next();
assert.equal(story(),'ch02_dispute');reveal();assert(html.includes('message-row npc'));assert(vm.runInContext("STORIES.ch02_dispute.dialogues.some(line=>line.speakerType==='player'&&line.alignment==='right')",context));next();assert.equal(story(),'ch02_trust');choose(0);assert.equal(current().run.relations.citizens,3);assert.equal(current().run.trust.doyun,9);assert(current().run.sharedEvents.includes('helped_doyun_friend'));
assert.equal(story(),'ch02_inspection');next();assert.equal(story(),'ch02_policy_reason');choose(0);assert(current().run.flags.understandsNobi);assert.equal(current().meta.knowledgeMemory['ch02-nobi-purpose'].correct,true);
assert.equal(story(),'ch02_policy_memory');next();drainSceneQuestions(["ch03-practice-nobi-basic","ch02-review-01","ch02-official-74-advanced-11"]);assert.equal(story(),'ch02_noble_night');assert.equal(current().run.activeQuestionId,null);
assert.equal(story(),'ch02_noble_night');next();drainSceneQuestions(['ch03-practice-nobi-power','ch03-pdf-73-advanced-11']);assert.equal(story(),'ch02_jump_958');next();assert.equal(story(),'ch02_exam_notice');assert.equal(current().run.characterStates.doyun.characterAge,64);reveal();assert(html.includes('hyunwoo_neutral'));next();assert.equal(story(),'ch02_three_way');assert(vm.runInContext("resolvedPortraitId(STORIES.ch02_three_way.dialogues.find(line=>line.characterId==='doyun'&&line.expression==='neutral'))==='doyun_956_neutral'",context));reveal();assert(html.includes('앞으로 셋이 자주 보자'));next();assert.equal(story(),'ch02_ssanggi');next();drainSceneQuestions(["ch02-test-02","ch03-practice-gwageo-purpose","ch02-official-78-advanced-11"]);assert.equal(story(),'ch02_exam_eve');assert.equal(current().run.activeQuestionId,null);
assert.equal(story(),'ch02_exam_eve');reveal();assert(html.includes('현우에게 무슨 말을'));choose(0);assert.equal(current().run.relations.hyunwoo,5);assert.equal(current().run.trust.hyunwoo,5);assert(current().run.sharedEvents.includes('supported_hyunwoo_exam'));
assert.equal(story(),'ch02_exam_day');next();drainSceneQuestions(['ch03-official-71-advanced-11','ch03-pdf-75-basic-10']);assert.equal(story(),'ch02_official_robes_walk');assert(html.includes('ch02-official-robes-street-960.png'));reveal();assert(!html.includes('character-stage'));next();assert.equal(story(),'ch02_hyunwoo_official');assert.equal(current().run.characterStates.hyunwoo.outfit,'young_official');assert(html.includes('data-character-id="hyunwoo"'));assert(html.includes('hyunwoo_smile'));reveal();assert(current().meta.cards.includes('gwangjong-official-robes'));next();drainSceneQuestions(['ch02-test-robes','ch03-pdf-68-advanced-09','ch03-pdf-76-advanced-18']);assert.equal(story(),'ch02_reign_titles');
assert.equal(story(),'ch02_reign_titles');assert(html.includes('speech-bubble'));assert(html.includes('들었소?'));assert(!html.includes('character-stage'));action('advance-dialogue');assert(html.includes('speech-bubble'));assert(html.includes('무엇을 말이오?'));assert(!html.includes('character-stage'));reveal();assert(html.includes('광종…….'));assert(current().meta.cards.includes('gwangjong-gwangdeok'));next();assert.equal(story(),'ch02_reign_followup');assert(html.includes('speech-bubble'));assert(html.includes('연호가 또 바뀌었다더군.'));assert(!html.includes('character-stage'));action('advance-dialogue');assert(html.includes('speech-bubble'));assert(html.includes('이번에는 준풍이랍니다.'));assert(!html.includes('character-stage'));reveal();assert(html.includes('광덕…… 준풍.'));next();drainSceneQuestions(["ch02-test-04","ch02-official-76-advanced-50","ch02-official-77-advanced-14"]);assert.equal(story(),'ch02_purge');assert(!html.includes('알 수 없는 기억'));assert(!current().meta.mysteries.includes('unknown-aging'));reveal();assert(html.includes('길상'));action('next');drainAddedQuestions();assert.equal(story(),'ch02_night_discussion');reveal();assert(html.includes('왕권 강화'));action('next');drainSceneQuestions(['ch02-test-06','ch03-official-68-advanced-11']);assert.equal(story(),'ch02_complete');
assert.equal(story(),'ch02_complete');assert(!current().run.completed);assert(vm.runInContext("STORIES.ch02_complete.dialogues.some(line=>line.dialogue.includes('사십 년이 넘었소'))",context));reveal();assert(!html.includes('character-stage'));next();assert.equal(story(),'ch02_night_reflection');assert(html.includes('ch02-water-reflection-958'));assert(vm.runInContext("STORIES.ch02_night_reflection.dialogues.some(line=>line.dialogue.includes('사십 년 전 그날과 같았다'))",context));reveal();next();assert.equal(story(),'ch02_mystery');reveal();assert(html.includes('[알 수 없는 기억]'));assert(html.includes('???'));assert(current().meta.mysteries.includes('unknown-aging'));assert(current().run.sharedEvents.includes('noticed_unchanged_appearance'));action('next');
assert.equal(story(),'ch02_memory_retrieval');reveal();assert(!html.includes('character-stage'));action('next');assert.equal(story(),'ch02_chapter_clear');reveal();assert(html.includes('CH.03 왕의 나라'));action('next');
assert(current().run.completed);assert.equal(story(),'ch02_chapter_clear');assert(html.includes('CHAPTER 03 CLEAR'));assert(html.includes('노비안검법'));assert(html.includes('과거제'));assert(html.includes('공복 제정'));assert(html.includes('광덕 · 준풍'));assert(html.includes('29 / 29 정답'));assert(current().meta.completedChapters.includes('ch01'));assert(current().meta.completedChapters.includes('ch03'));
const runBeforeReview=JSON.parse(JSON.stringify(current().run)),reviewIds=vm.runInContext('SPLIT_REVIEW_IDS.ch03',context);click({action:'start-ch01-review',reviewChapter:'ch03'});assert.equal(vm.runInContext('reviewQuestionId',context),reviewIds[0]);answer(vm.runInContext('QUESTIONS.find(q=>q.questionId===reviewQuestionId).answer',context));action('quiz-next');assert.equal(vm.runInContext('reviewQuestionId',context),reviewIds[1]);const secondAnswer=vm.runInContext('QUESTIONS.find(q=>q.questionId===reviewQuestionId).answer',context);answer((secondAnswer+1)%5);assert(html.includes('기억이 흐릿하다'));boot();click({action:'start-ch01-review',reviewChapter:'ch03'});assert(html.includes('feedback'));action('quiz-next');for(const id of reviewIds.slice(2)){assert.equal(vm.runInContext('reviewQuestionId',context),id);answer(vm.runInContext('QUESTIONS.find(q=>q.questionId===reviewQuestionId).answer',context));action('quiz-next')}const reviewAttempt=current().meta.ch01ReviewAttempts.at(-1);assert.equal(reviewAttempt.chapterId,'ch03');assert.equal(reviewAttempt.correct,35);assert.equal(reviewAttempt.total,36);assert.deepEqual(current().run,runBeforeReview);assert(current().meta.wrongQuestionIds.includes(reviewIds[1]));click({review:reviewIds[1]});answer(vm.runInContext('QUESTIONS.find(q=>q.questionId===reviewQuestionId).answer',context));action('quiz-next');assert(current().meta.reviewedQuestionIds.includes(reviewIds[1]));
nav('teaser');assert(html.includes('CHAPTER 04 · UNLOCKED'));assert(html.includes('시무 28조'));assert(html.includes('CH.04 시작하기'));
nav('complete');action('request-replay');assert(html.includes('CH.03을 다시 플레이할까요?'));assert(html.includes('이미 완료한 이후 챕터의 진행 기록은 유지됩니다.'));click({action:'confirm-replay',chapter:'ch03'});assert.equal(current().run.mode,'replay');assert.equal(current().run.currentChapter,'ch03');assert.equal(story(),'ch02_transition');assert.equal(current().run.stats.wealth,24);assert.equal(current().run.job,'상단 장부 보조');assert.equal(current().run.relations.doyun,19);assert.equal(current().run.choices.length,0);assert(current().meta.completedChapters.includes('ch01'));assert(current().meta.completedChapters.includes('ch03'));
boot();action('play');assert.equal(current().run.currentChapter,'ch03');assert.equal(story(),'ch02_transition');
console.log('PASS: CH.03 transitions, aged portraits, preserved choice arcs, twenty-nine questions across fifteen sets, thirty-six-question review, delayed mystery reveal, wrong-note save, teaser, reload, and replay start.');
