const fs=require('fs'),vm=require('vm'),assert=require('assert');
let saved=null,html='',handlers={},context,timers=[];
const data=fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/ch02-data.js','utf8')+'\n'+fs.readFileSync('dist/ch03-data.js','utf8')+'\n'+fs.readFileSync('dist/exam-data.js','utf8')+'\n'+fs.readFileSync('dist/ch01-expansion.js','utf8')+'\n'+fs.readFileSync('dist/chapter-split.js','utf8'),app=fs.readFileSync('dist/app.js','utf8');
function boot(){handlers={};timers=[];const root={set innerHTML(s){html=s},get innerHTML(){return html}};const document={querySelector:s=>s==='#app'?root:null,querySelectorAll:()=>[],addEventListener:(e,f)=>handlers[e]=f,createElement:()=>({setAttribute(){},remove(){}}),body:{append(){}}};context=vm.createContext({document,localStorage:{getItem:()=>saved,setItem:(k,s)=>saved=s},window:{scrollTo(){}},navigator:{},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},Date});vm.runInContext(data+app,context)}
const click=dataset=>{vm.runInContext('inputLockedUntil=0',context);handlers.click({target:{closest:()=>({dataset,disabled:false})}})},action=x=>click({action:x}),nav=x=>click({nav:x}),selectChoice=i=>click({choice:String(i)}),answer=i=>click({answer:String(i)});
const current=()=>JSON.parse(saved),story=()=>current().run.storyId;
function reveal(){let n=0;while(html.includes('data-action="advance-dialogue"')){action('advance-dialogue');if(++n>15)throw Error('dialogue guard')}}
function next(){reveal();action('next')}function choose(i){reveal();selectChoice(i);reveal();action('result-next')}
function drainSupplementalQuestions(){let guard=0;while(vm.runInContext(`Boolean(STORIES[${JSON.stringify(story())}]?.supplementalExam)`,context)){next();const correct=vm.runInContext('QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer',context);answer(correct);assert(html.includes('기억이 선명해졌다'));action('quiz-next');if(++guard>8)throw new Error('supplemental quiz guard')}}
function answerAndContinue(i){answer(i);assert(html.includes(i===vm.runInContext(`QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer`,context)?'기억이 선명해졌다':'기억이 흐릿하다'));action('quiz-next');drainSupplementalQuestions()}

boot();
vm.runInContext("state.run.started=true;state.run.stats={health:88,knowledge:11,fame:6,wealth:24};state.run.relations.doyun=19;state.run.job='상단 장부 보조';state.run.route='merchant';finishChapter(state);if(state.run.currentChapter==='ch01'){startChapter(state,'ch02');finishChapter(state);}save();",context);
nav('teaser');assert(html.includes('CHAPTER 03 · UNLOCKED'));click({action:'start-chapter',chapter:'ch03'});
assert.equal(current().run.currentChapter,'ch03');assert.equal(story(),'ch02_transition');assert.equal(current().run.stats.wealth,24);assert.equal(current().run.job,'상단 장부 보조');assert(html.includes('CH.03'));
assert.equal(current().run.playerOutfit,'goryeo_commoner');assert.equal(current().run.flags.wearingModernClothes,false);assert.equal(current().run.characterStates.doyun.ageVariant,'middle_aged_949');assert.equal(current().run.characterStates.doyun.characterAge,57);assert(vm.runInContext("STORIES.ch02_transition.dialogues.map(x=>x.dialogue).join('|').includes('918년 — 고려 건국')&&STORIES.ch02_transition.dialogues.map(x=>x.dialogue).join('|').includes('949년 — 개경')",context));
next();assert.equal(story(),'ch02_shop_exterior_949');assert(html.includes('ch02-doyun-shop-exterior-949'));next();assert.equal(story(),'ch02_reunion_949');reveal();assert(!html.includes('character-stage'));assert(html.includes('data-speaker-type="thought"'));next();assert.equal(story(),'ch02_market');reveal();assert(!html.includes('character-stage'));assert(vm.runInContext("STORIES.ch02_market.dialogues.some(line=>line.speakerType==='npc')",context));choose(0);assert.equal(current().meta.knowledgeMemory['ch02-king-after-taejo'].answer,'광종');
assert.equal(story(),'ch02_life_path');choose(0);assert.equal(current().run.lifePath,'doyun-merchant-partner');assert(current().run.sharedEvents.includes('helped_doyun_business'));assert.equal(story(),'ch02_jump_956');next();assert.equal(story(),'ch02_shop_956');assert.equal(current().run.characterStates.doyun.ageVariant,'elder_956');assert.equal(current().run.characterStates.doyun.characterAge,64);reveal();assert(!html.includes('character-stage'));next();
assert.equal(story(),'ch02_dispute');reveal();assert(html.includes('message-row npc'));assert(vm.runInContext("STORIES.ch02_dispute.dialogues.some(line=>line.speakerType==='player'&&line.alignment==='right')",context));next();assert.equal(story(),'ch02_trust');choose(0);assert.equal(current().run.relations.citizens,3);assert.equal(current().run.trust.doyun,9);assert(current().run.sharedEvents.includes('helped_doyun_friend'));
assert.equal(story(),'ch02_inspection');next();assert.equal(story(),'ch02_policy_reason');choose(0);assert(current().run.flags.understandsNobi);assert.equal(current().meta.knowledgeMemory['ch02-nobi-purpose'].correct,true);
assert.equal(story(),'ch02_policy_memory');next();assert.equal(current().run.activeQuestionId,'ch02-test-01');answerAndContinue(0);assert(current().meta.wrongQuestionIds.includes('ch02-test-01'));
assert.equal(story(),'ch02_noble_night');next();assert.equal(story(),'ch02_jump_958');next();assert.equal(story(),'ch02_exam_notice');assert.equal(current().run.characterStates.doyun.characterAge,66);reveal();assert(html.includes('hyunwoo_neutral'));next();assert.equal(story(),'ch02_three_way');assert(vm.runInContext("resolvedPortraitId(STORIES.ch02_three_way.dialogues.find(line=>line.characterId==='doyun'&&line.expression==='neutral'))==='doyun_956_neutral'",context));reveal();assert(html.includes('앞으로 셋이 자주 보자'));next();assert.equal(story(),'ch02_ssanggi');next();answerAndContinue(0);
assert.equal(story(),'ch02_exam_eve');reveal();assert(html.includes('현우에게 무슨 말을'));choose(0);assert.equal(current().run.relations.hyunwoo,5);assert.equal(current().run.trust.hyunwoo,5);assert(current().run.sharedEvents.includes('supported_hyunwoo_exam'));
assert.equal(story(),'ch02_exam_day');next();assert.equal(story(),'ch02_official_robes_walk');assert(html.includes('ch02-official-robes-street-960.png'));reveal();assert(!html.includes('character-stage'));next();assert.equal(story(),'ch02_hyunwoo_official');assert.equal(current().run.characterStates.hyunwoo.outfit,'young_official');assert(html.includes('data-character-id="hyunwoo"'));assert(html.includes('hyunwoo_smile'));reveal();assert(current().meta.cards.includes('gwangjong-official-robes'));next();answerAndContinue(1);
assert.equal(story(),'ch02_reign_titles');assert(html.includes('상인 A'));assert(html.includes('들었소?'));assert(!html.includes('character-stage'));assert(!html.includes('data-character-id="merchant"'));action('advance-dialogue');assert(html.includes('상인 B'));assert(html.includes('무엇을 말이오?'));assert(!html.includes('character-stage'));reveal();assert(html.includes('광종…….'));assert(current().meta.cards.includes('gwangjong-gwangdeok'));next();answerAndContinue(0);assert.equal(story(),'ch02_reign_followup');assert(html.includes('상인 A'));assert(html.includes('연호가 또 바뀌었다더군.'));assert(!html.includes('character-stage'));action('advance-dialogue');assert(html.includes('상인 B'));assert(html.includes('이번에는 준풍이랍니다.'));assert(!html.includes('character-stage'));reveal();assert(html.includes('광덕…… 준풍.'));next();answerAndContinue(1);assert.equal(story(),'ch02_purge');assert(!html.includes('알 수 없는 기억'));assert(!current().meta.mysteries.includes('unknown-aging'));reveal();assert(html.includes('길상'));action('next');assert.equal(story(),'ch02_night_discussion');reveal();assert(html.includes('왕권 강화'));action('next');answerAndContinue(0);
assert.equal(story(),'ch02_complete');assert(!current().run.completed);assert(vm.runInContext("STORIES.ch02_complete.dialogues.some(line=>line.dialogue.includes('사십 년이 넘었소'))",context));reveal();assert(!html.includes('character-stage'));next();assert.equal(story(),'ch02_night_reflection');assert(html.includes('ch02-water-reflection-958'));assert(vm.runInContext("STORIES.ch02_night_reflection.dialogues.some(line=>line.dialogue.includes('사십 년 전 그날과 같았다'))",context));reveal();next();assert.equal(story(),'ch02_mystery');reveal();assert(html.includes('[알 수 없는 기억]'));assert(html.includes('???'));assert(current().meta.mysteries.includes('unknown-aging'));assert(current().run.sharedEvents.includes('noticed_unchanged_appearance'));action('next');
assert.equal(story(),'ch02_memory_retrieval');reveal();assert(!html.includes('character-stage'));action('next');answerAndContinue(1);assert.equal(story(),'ch02_realization');reveal();assert(html.includes('광종 → 왕권 강화'));action('next');assert.equal(story(),'ch02_chapter_clear');reveal();assert(html.includes('CH.03 왕의 나라'));action('next');
assert(current().run.completed);assert.equal(story(),'ch02_chapter_clear');assert(html.includes('CHAPTER 03 CLEAR'));assert(html.includes('노비안검법'));assert(html.includes('과거제'));assert(html.includes('공복 제정'));assert(html.includes('광덕 · 준풍'));assert(html.includes('5문제'));assert(current().meta.completedChapters.includes('ch01'));assert(current().meta.completedChapters.includes('ch03'));
const runBeforeReview=JSON.parse(JSON.stringify(current().run));click({action:'start-ch01-review',reviewChapter:'ch03'});assert.equal(vm.runInContext('reviewQuestionId',context),'ch02-review-01');answer(vm.runInContext('QUESTIONS.find(q=>q.questionId===reviewQuestionId).answer',context));action('quiz-next');assert.equal(vm.runInContext('reviewQuestionId',context),'ch02-review-02');answer(0);assert(html.includes('기억이 흐릿하다'));boot();click({action:'start-ch01-review',reviewChapter:'ch03'});assert(html.includes('feedback'));action('quiz-next');for(const id of ['ch02-review-03','ch02-review-04','ch02-review-05']){assert.equal(vm.runInContext('reviewQuestionId',context),id);answer(vm.runInContext('QUESTIONS.find(q=>q.questionId===reviewQuestionId).answer',context));action('quiz-next')}const reviewAttempt=current().meta.ch01ReviewAttempts.at(-1);assert.equal(reviewAttempt.chapterId,'ch03');assert.equal(reviewAttempt.correct,4);assert.equal(reviewAttempt.total,5);assert.deepEqual(current().run,runBeforeReview);assert(current().meta.wrongQuestionIds.includes('ch02-review-02'));click({review:'ch02-review-02'});answer(vm.runInContext('QUESTIONS.find(q=>q.questionId===reviewQuestionId).answer',context));action('quiz-next');assert(current().meta.reviewedQuestionIds.includes('ch02-review-02'));
nav('teaser');assert(html.includes('CHAPTER 04 · UNLOCKED'));assert(html.includes('시무 28조'));assert(html.includes('CH.04 시작하기'));
nav('complete');action('request-replay');assert(html.includes('CH.03을 다시 플레이할까요?'));assert(html.includes('이미 완료한 이후 챕터의 진행 기록은 유지됩니다.'));click({action:'confirm-replay',chapter:'ch03'});assert.equal(current().run.mode,'replay');assert.equal(current().run.currentChapter,'ch03');assert.equal(story(),'ch02_transition');assert.equal(current().run.stats.wealth,24);assert.equal(current().run.job,'상단 장부 보조');assert.equal(current().run.relations.doyun,19);assert.equal(current().run.choices.length,0);assert(current().meta.completedChapters.includes('ch01'));assert(current().meta.completedChapters.includes('ch03'));
boot();action('play');assert.equal(current().run.currentChapter,'ch03');assert.equal(story(),'ch02_transition');
console.log('PASS: CH.03 918→949→956→958→960 transitions, aged Doyun and young-official Hyunwoo portraits, preserved choice arcs, 12 story tests, five-question review entry, delayed mystery reveal, memory-retrieval clear, wrong-note save, CH.04 teaser, reload, and replay start.');
