const fs=require('fs'),vm=require('vm'),assert=require('assert');
let saved=null,html='',handlers={},context,timers=[];
const data=fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/ch02-data.js','utf8')+'\n'+fs.readFileSync('dist/ch03-data.js','utf8')+'\n'+fs.readFileSync('dist/exam-data.js','utf8')+'\n'+fs.readFileSync('dist/ch01-expansion.js','utf8')+'\n'+fs.readFileSync('dist/chapter-split.js','utf8'),app=fs.readFileSync('dist/app.js','utf8');
function boot(){handlers={};timers=[];const root={set innerHTML(s){html=s},get innerHTML(){return html}};const document={querySelector:s=>s==='#app'?root:null,querySelectorAll:()=>[],addEventListener:(e,f)=>handlers[e]=f,createElement:()=>({setAttribute(){},remove(){}}),body:{append(){}}};context=vm.createContext({document,localStorage:{getItem:()=>saved,setItem:(k,s)=>saved=s},window:{scrollTo(){}},navigator:{},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},Date});vm.runInContext(data+app,context)}
const click=dataset=>{vm.runInContext('inputLockedUntil=0',context);handlers.click({target:{closest:()=>({dataset,disabled:false})}})},action=x=>click({action:x}),nav=x=>click({nav:x}),selectChoice=i=>click({choice:String(i)}),answer=i=>click({answer:String(i)});
const current=()=>JSON.parse(saved),story=()=>current().run.storyId;
function reveal(){let n=0;while(html.includes('data-action="advance-dialogue"')){action('advance-dialogue');if(++n>20)throw Error('dialogue guard')}}
function next(){reveal();action('next')}function choose(i){reveal();selectChoice(i);reveal();action('result-next')}
function drainSupplementalQuestions(){let guard=0;while(vm.runInContext(`Boolean(STORIES[${JSON.stringify(story())}]?.supplementalExam)`,context)){next();const correct=vm.runInContext('QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer',context);answer(correct);assert(html.includes('기억이 선명해졌다'));action('quiz-next');if(++guard>8)throw new Error('supplemental quiz guard')}}
function answerAndContinue(i){answer(i);assert(html.includes(i===vm.runInContext('QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer',context)?'기억이 선명해졌다':'기억이 흐릿하다'));action('quiz-next');drainSupplementalQuestions()}

boot();
vm.runInContext("state.run.started=true;state.run.stats={health:81,knowledge:18,fame:9,wealth:37};state.run.relations.doyun=31;state.run.relations.hyunwoo=14;state.run.job='도윤상단 장부 책임자';finishChapter(state);if(state.run.currentChapter==='ch01'){startChapter(state,'ch02');finishChapter(state);}startChapter(state,'ch03');state.run.stats.wealth=52;state.run.relations.doyun=44;state.run.relations.hyunwoo=22;finishChapter(state);save();",context);
nav('teaser');assert(html.includes('CHAPTER 04 · UNLOCKED'));assert(html.includes('CH.04 시작하기'));click({action:'start-chapter',chapter:'ch04'});
assert.equal(current().run.currentChapter,'ch04');assert.equal(story(),'ch03_transition');assert.equal(current().run.stats.wealth,52);assert.equal(current().run.playerOutfit,'goryeo_commoner');assert.equal(current().run.characterStates.doyun.ageVariant,'elder_982');assert.equal(current().run.characterStates.hyunwoo.ageVariant,'middle_982');
assert(vm.runInContext("STORIES.ch03_transition.dialogues.map(x=>x.dialogue).join('|').includes('계절이 또 수십 번 바뀌었다.')&&STORIES.ch03_transition.dialogues.at(-1).dialogue==='982년 — 개경'",context));
next();assert.equal(story(),'ch03_gaegyeong');assert(html.includes('ch03-gaegyeong-982'));next();assert.equal(story(),'ch03_guild_exterior');assert(html.includes('도윤상단'));next();assert.equal(story(),'ch03_dream_realized');assert.equal(vm.runInContext("resolvedPortraitId(STORIES.ch03_dream_realized.dialogues.find(x=>x.expression==='laugh'))",context),'doyun_old_laugh');assert(vm.runInContext("STORIES.ch03_dream_realized.dialogues.some(x=>x.dialogue==='결국 만들었네.')",context));reveal();next();
assert.equal(story(),'ch03_unchanged');reveal();assert(html.includes('data-speaker-type="thought"'));assert(vm.runInContext("STORIES.ch03_unchanged.dialogues.some(x=>x.dialogue==='나는 도대체 언제까지 여기서 살아야 하지?')",context));next();
assert.equal(story(),'ch03_returning_merchant');next();assert.equal(story(),'ch03_provincial_problem');next();assert.equal(story(),'ch03_policy_choice');reveal();assert(html.includes('왕이 직접 관리하는 사람을 지방에 보내야 하지 않을까?'));choose(0);assert.equal(story(),'ch03_hyunwoo_return');assert.equal(current().run.importantChoices.ch03_policy_choice,'royal-local-officials');assert(current().run.sharedEvents.includes('proposed_local_officials'));
boot();action('play');assert.equal(story(),'ch03_hyunwoo_return');assert.equal(vm.runInContext("resolvedPortraitId(STORIES.ch03_hyunwoo_return.dialogues.find(x=>x.characterId==='hyunwoo'&&x.expression==='serious'))",context),'hyunwoo_middle_serious');reveal();assert(html.includes('둘이 아직도 저러네.'));next();
assert.equal(story(),'ch03_seongjong_news');reveal();assert(html.includes('HISTORY DISCOVERED'));assert(current().meta.people.includes('성종'));next();assert.equal(story(),'ch03_choe_reform');reveal();assert(html.includes('최승로 · 시무 28조'));assert(current().meta.people.includes('최승로'));next();
assert.equal(story(),'ch03_twelve_mok');reveal();assert(html.includes('12목 지방관 파견'));next();assert.equal(story(),'ch03_gukjagam');reveal();assert(html.includes('고려의 최고 교육 기관'));assert(current().meta.cards.includes('gukjagam'));next();const storySet=vm.runInContext('SPLIT_STORY_QUESTION_IDS.ch04',context);for(let i=0;i<storySet.length;i++){assert.equal(current().run.activeQuestionId,storySet[i]);assert(html.includes(`실제 기출 ${i+1} / 3`));assert(html.includes('ACTUAL EXAM'));answerAndContinue(vm.runInContext('QUESTIONS.find(q=>q.questionId===run().activeQuestionId).answer',context))}
assert.equal(story(),'ch03_policy_effect');next();assert.equal(story(),'ch03_three_friends');next();assert.equal(story(),'ch03_history_reflection');next();assert.equal(story(),'ch03_courtyard');assert(html.includes('ch03-doyun-courtyard'));next();assert.equal(story(),'ch03_weakening');next();assert.equal(story(),'ch03_farewell');assert(html.includes('ch03-doyun-farewell'));reveal();assert(html.includes('얼마나 더 살아야 하는 거요?'));next();assert.equal(story(),'ch03_doyun_soliloquy');reveal();assert(html.includes('나쁘지 않은 장사였소.'));assert(!current().run.activeQuestionId);next();assert.equal(story(),'ch03_death');next();assert.equal(story(),'ch03_legacy');assert.equal(current().run.characterStates.doyun.isAlive,false);assert.equal(current().run.doyunLegacy.name,'도윤상단');reveal();action('next');
assert(current().run.completed);assert(current().meta.completedChapters.includes('ch04'));assert.equal(current().run.characterStates.doyun.deathCause,'old_age');assert.equal(current().run.doyunLegacy.merchantGuild,true);assert(html.includes('CHAPTER 04 COMPLETE'));assert(html.includes('이번에 경험한 역사'));assert(html.includes('당신의 고려 이야기'));assert(html.includes('3개 연계'));
nav('teaser');assert(html.includes('CHAPTER 05 · NEXT'));assert(html.includes('거란의 침입'));
boot();action('play');assert(html.includes('CHAPTER 04 COMPLETE'));assert(current().meta.questionRecords['ch03-official-75-basic-10'].attempts===1);
console.log('PASS: CH.04 982 time jump, aged portraits, Seongjong 3-question official set, uninterrupted Doyun farewell/soliloquy/legacy, teaser, save, and reload.');
