const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const code=fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/ch02-data.js','utf8')+'\n'+fs.readFileSync('dist/ch03-data.js','utf8')+'\n'+fs.readFileSync('dist/exam-data.js','utf8')+'\n'+fs.readFileSync('dist/ch01-expansion.js','utf8')+'\n'+fs.readFileSync('dist/chapter-split.js','utf8')+'\n'+fs.readFileSync('dist/late-goryeo.js','utf8')+'\n'+fs.readFileSync('dist/official-late-exams.js','utf8');
const ctx=vm.createContext({Date});
vm.runInContext(code+';this.api={SAVE_VERSION,CHAPTERS,STORIES,QUESTIONS,QUESTION_SETS,ASSETS,EXPRESSIONS,PORTRAITS,CHARACTERS,CHARACTER_ASSET_MAP,SPLIT_STORY_QUESTION_IDS,SPLIT_REVIEW_IDS,INITIAL,INITIAL_RUN,applyChoice,applySceneEntry,applyDialogueMilestone,choiceAvailable,recordQuestion,finishChapter,resetRun,setPlayerOutfit,startChapter,restartChapter,beginReplay,restoreMainRun,migrateSave};',ctx);
const{SAVE_VERSION,CHAPTERS,STORIES,QUESTIONS,QUESTION_SETS,ASSETS,EXPRESSIONS,PORTRAITS,CHARACTERS,CHARACTER_ASSET_MAP,SPLIT_STORY_QUESTION_IDS,SPLIT_REVIEW_IDS,INITIAL,applyChoice,applySceneEntry,applyDialogueMilestone,choiceAvailable,recordQuestion,finishChapter,startChapter,restartChapter,beginReplay,restoreMainRun,migrateSave}=ctx.api;
  assert.equal(SAVE_VERSION,15);
  assert.equal(Object.keys(CHAPTERS).length,12);assert(Object.values(CHAPTERS).every(chapter=>chapter.implemented));assert.equal(CHAPTERS.ch12.title,'고려의 마지막');
assert.equal(QUESTIONS.filter(q=>q.chapterId==='ch03'&&!q.reviewOnly&&!q.retired).length,3,'CH.03 keeps one verified three-question learning set');
assert.equal(QUESTIONS.filter(q=>q.chapterId==='ch04'&&!q.reviewOnly&&!q.retired).length,3,'CH.04 keeps one verified three-question learning set');
const protectedQuestionFields=['questionId','passage','question','choices','answer','explanation','examKeywords','relatedSceneId','resumeStoryId'];
const originalQuestion=q=>{const copy={...q};if(copy.originalResumeStoryId){copy.resumeStoryId=copy.originalResumeStoryId;delete copy.originalResumeStoryId}return copy};
const protectedCh02Questions=QUESTIONS.filter(q=>['ch02-test-01','ch02-test-02'].includes(q.questionId)).map(originalQuestion).map(q=>Object.fromEntries(protectedQuestionFields.map(field=>[field,q[field]])));
  assert.equal(crypto.createHash('sha256').update(JSON.stringify(protectedCh02Questions)).digest('hex'),'a73cb25aadb9be2cd883b8c0a8a1980a37e7e2a9041c848092f7146b0d36623b','CH.03 pre-exam protected problem data changed');
// Full content preservation is checked by chapter-split-protected.json after chapter ownership changes.
const requiredQuestionFields=['questionId','chapterId','relatedSceneId','relatedHistoricalEventId','relatedIllustrationId','questionType','difficulty','passage','question','choices','answer','explanation','examKeywords','userAnswer','isCorrect','isOfficial','source','examRound','examYear','questionNumber'];
for(const q of QUESTIONS){
  for(const field of requiredQuestionFields)assert(Object.prototype.hasOwnProperty.call(q,field),`${q.questionId}: missing ${field}`);
  assert(q.answer>=0&&q.answer<q.choices.length,`${q.questionId}: invalid answer`);
  if(q.isOfficial){assert(Number.isInteger(q.examRound)&&Number.isInteger(q.examYear)&&Number.isInteger(q.questionNumber),`${q.questionId}: official metadata required`);assert(['기본','심화'].includes(q.examLevel),`${q.questionId}: exam level required`);assert(q.source.includes('사용자 제공 문제지·정답표 기반'));assert(q.sourceFile.endsWith('.pdf')&&!/[\\/]/.test(q.sourceFile),`${q.questionId}: source must be a portable PDF filename`);assert(q.answerFile.endsWith('.pdf')&&!/[\\/]/.test(q.answerFile),`${q.questionId}: answer must be a portable PDF filename`)}
  assert(STORIES[q.relatedSceneId],`${q.questionId}: missing related scene`);
  assert(ASSETS[q.relatedIllustrationId],`${q.questionId}: missing related illustration`);
  assert(STORIES[q.resumeStoryId],`${q.questionId}: missing resume scene`);
  if(!q.retired){assert(['official_exam','exam_style','original_advanced_practice'].includes(q.sourceType),`${q.questionId}: sourceType required`);assert(Array.isArray(q.conceptIds),`${q.questionId}: conceptIds required`)}
}
for(const[id,s]of Object.entries(STORIES)){
  assert.equal(s.sceneId,id,`${id}: sceneId mismatch`);assert(ASSETS[s.illustrationId],`${id}: missing illustration`);
  if(s.nextStoryId)assert(STORIES[s.nextStoryId],`${id}: missing next scene ${s.nextStoryId}`);
  if(s.quizId)assert(QUESTIONS.some(q=>q.questionId===s.quizId),`${id}: missing quiz ${s.quizId}`);
  for(const qid of s.linkedQuestionIds||[])assert(QUESTIONS.some(q=>q.questionId===qid&&!q.retired),`${id}: missing linked question ${qid}`);
  assert(Array.isArray(s.dialogues)&&s.dialogues.length,`${id}: structured dialogues required`);
  for(const line of s.dialogues){
    for(const field of ['characterId','characterName','speakerType','portrait','expression','dialogue','alignment'])assert(Object.prototype.hasOwnProperty.call(line,field),`${id}: dialogue missing ${field}`);
    assert(['player','npc','thought','narration'].includes(line.speakerType),`${id}: unsupported speaker type`);assert(EXPRESSIONS.includes(line.expression),`${id}: unsupported expression ${line.expression}`);
    assert.equal(line.alignment,line.speakerType==='player'?'right':line.speakerType==='npc'?'left':'center',`${id}: alignment must derive from speakerType`);
    if(['player','npc'].includes(line.speakerType))assert(PORTRAITS[line.portrait],`${id}: missing portrait ${line.portrait}`);
    if(['player','npc'].includes(line.speakerType)&&CHARACTERS[line.characterId]?.show!==false){const portrait=PORTRAITS[line.portrait];assert.equal(portrait.status,'ready',`${id}: portrait is not ready: ${line.portrait}`);assert(portrait.src&&fs.existsSync('dist/'+portrait.src),`${id}: portrait file missing: ${line.portrait}`)}
  }
  for(const c of s.choices||[]){assert(STORIES[c.nextStoryId],`${id}: missing choice destination`);assert(c.resultSceneId&&ASSETS[c.resultIllustrationId],`${id}: result scene/illustration required`);assert(Array.isArray(c.resultDialogues)&&c.resultDialogues.length>=2,`${id}: player response and reaction required`);assert.equal(c.resultDialogues[0].speakerType,'player');for(const line of c.resultDialogues.filter(line=>['player','npc'].includes(line.speakerType)&&CHARACTERS[line.characterId]?.show!==false)){const portrait=PORTRAITS[line.portrait];assert.equal(portrait?.status,'ready',`${id}: choice portrait is not ready: ${line.portrait}`);assert(portrait.src&&fs.existsSync('dist/'+portrait.src),`${id}: choice portrait file missing: ${line.portrait}`)}}
}
for(const [id,character] of Object.entries(CHARACTERS)){assert(['left','right','center'].includes(character.position),`${id}: default position required`);assert.equal(typeof character.show,'boolean',`${id}: explicit show flag required`)}
assert.equal(CHARACTERS.doyun.position,'left');assert.equal(CHARACTERS.player.position,'right');assert.equal(CHARACTERS.merchant.position,'left');assert.equal(CHARACTERS.unknown.show,false);assert.equal(CHARACTERS.narrator.show,false);
const ambientCharacterIds=['stranger','resident_a','resident_b','elder','child','merchant','steward','official','noble','citizen','soldier'];for(const id of ambientCharacterIds){assert.equal(CHARACTERS[id].show,false,`${id}: ambient NPC must not show a standing portrait`);assert.equal(CHARACTERS[id].presentation,'ambient',`${id}: ambient presentation required`)}
for(const id of ['player','doyun','merchant_01','freed_man','hyunwoo']){assert.equal(CHARACTERS[id].show,true,`${id}: recurring character standing must remain enabled`);assert.equal(CHARACTERS[id].presentation,'standing',`${id}: standing presentation required`)}
assert.equal(CHARACTERS.injured_merchant.show,false);assert.equal(CHARACTERS.injured_merchant.replacedBy,'merchant_01');
for(const id of ['rumor','market','ch01_gochang','ch02_reign_titles','ch02_reign_followup']){assert.deepEqual(Array.from(STORIES[id].visibleCharacters),[],`${id}: ambient scene must explicitly hide layered characters`);assert.equal(STORIES[id].sceneType,'ambient-rumor')}
assert.deepEqual(Array.from(STORIES.foundation.visibleCharacters),[]);assert.equal(STORIES.foundation.sceneType,'thought');
assert(STORIES.ch01_gyeonhwon.visibleCharacters.includes('merchant_01'));assert(STORIES.ch01_gyeonhwon.visibleCharacters.includes('doyun'));assert(!STORIES.ch02_exam_notice.visibleCharacters.includes('citizen'));assert(STORIES.ch02_exam_notice.visibleCharacters.includes('hyunwoo'));
assert.deepEqual(STORIES.ch02_reign_titles.dialogues.filter(line=>line.speakerType==='npc').map(line=>line.characterName),['상인 A','상인 B','상인 A','상인 B']);assert(STORIES.ch02_reign_titles.dialogues.some(line=>line.speakerType==='thought'&&line.dialogue==='광덕.'));assert.deepEqual(STORIES.ch02_reign_followup.dialogues.filter(line=>line.speakerType==='npc').map(line=>line.characterName),['상인 A','상인 B']);assert(STORIES.ch02_reign_followup.dialogues.some(line=>line.speakerType==='thought'&&line.dialogue==='광덕…… 준풍.'));assert.equal(STORIES.ch02_reign_titles.illustrationId,'ch02-gaegyeong-market');assert.equal(STORIES.ch02_reign_followup.illustrationId,'ch02-gaegyeong-market');
for(const file of ['merchant_01.png','injured_merchant_01.png','merchant_01_935.png','doyun_935.png','doyun_943.png','villager_male_01.png','villager_female_01.png','villager_old_01.png','villager_child_01.png','official_01.png','laborer_01.png','noble_01.png','soldier_01.png','steward_01.png'])assert(fs.existsSync('dist/assets/characters/'+file),`missing reusable NPC asset: ${file}`);
assert.deepEqual(STORIES.status.dialogues.map(x=>x.speakerType),['npc','player','npc','player','thought']);
assert.equal(STORIES.voice.sceneEffect,'blackout');assert.equal(STORIES.voice.autoAdvanceDelays,undefined);assert.equal(STORIES.voice.dialogues.length,2);
assert.equal(STORIES.outfit_question.storyActive,false);assert.equal(STORIES.house.choices,undefined);assert.equal(STORIES.house.nextStoryId,'outfit_gift');assert.equal(STORIES.outfit_gift.outfitChange.dialogueIndex,8);assert.equal(STORIES.outfit_gift.outfitChange.to,'goryeo_commoner');assert(!STORIES.outfit_gift.enterFlags);
assert.deepEqual(Array.from(STORIES.foundation.linkedQuestionIds),['ch01-official-69-basic-10','ch01-official-79-advanced-09']);assert.equal(STORIES.foundation.questionSetStatus,'ready');assert.equal(STORIES.ch01_gongsan.linkedQuestionIds,undefined);assert.equal(STORIES.ch01_gochang.linkedQuestionIds,undefined);
assert(QUESTIONS.filter(q=>q.chapterId==='ch01'&&!q.retired).every(q=>q.isOfficial&&q.sourceVerified&&q.questionAuditStatus==='VERIFIED_OFFICIAL'));
assert.deepEqual(Array.from(SPLIT_STORY_QUESTION_IDS.ch01),['ch01-official-69-basic-10','ch01-official-79-advanced-09']);
assert.deepEqual(Array.from(SPLIT_REVIEW_IDS.ch01),['ch01-official-69-basic-10','ch01-official-79-advanced-09']);
assert.equal(STORIES.ch01_gongsan.officialQuestionSlot.officialQuestionStatus,'waiting_for_source');assert(STORIES.ch01_gongsan.visibleCharacters.includes('merchant_01'));assert.equal(STORIES.ch01_gongsan.enterCharacterStates.merchant_01.variant,'injured');
assert.deepEqual(Array.from(SPLIT_STORY_QUESTION_IDS.ch02),['ch01-official-76-advanced-10','ch01-official-74-advanced-10','ch01-official-70-advanced-10','ch02-official-67-basic-10','ch03-official-75-basic-12','ch02-official-65-advanced-10']);assert(SPLIT_STORY_QUESTION_IDS.ch02.every(id=>QUESTIONS.find(q=>q.questionId===id)?.isOfficial));assert.equal(SPLIT_REVIEW_IDS.ch02.length,10);
assert.equal(STORIES.life_choice.choices.length,4);assert.equal(STORIES.ch02_market.choices.length,4);assert.equal(STORIES.ch02_life_path.choices.length,3);assert.equal(STORIES.ch02_trust.choices.length,3);assert(STORIES.ch02_trust.choices.every(c=>c.importantChoice));assert.equal(STORIES.ch02_policy_reason.choices[0].memoryKey,'ch02-nobi-purpose');assert(STORIES.ch02_exam_notice.dialogues.some(x=>x.characterId==='hyunwoo'));assert(STORIES.ch02_three_way.dialogues.some(x=>x.characterId==='doyun'));assert(!STORIES.ch02_unchanged);assert(!STORIES.ch02_reflection);assert(!ASSETS['ch02-reflection']);assert(STORIES.ch02_night_reflection);assert(STORIES.ch02_mystery.mysteryKey==='unknown-aging'&&!STORIES.ch02_mystery.completeChapter);assert.equal(STORIES.ch02_mystery.nextStoryId,'ch02_memory_retrieval');assert(STORIES.ch02_chapter_clear.completeChapter);assert.equal(QUESTIONS.find(q=>q.questionId==='ch02-test-04').originalResumeStoryId,'ch02_purge');assert(STORIES.ch02_purge.dialogues.some(x=>x.characterId==='freed_man'));assert(STORIES.ch02_night_discussion.dialogues.some(x=>x.characterId==='hyunwoo'));assert(STORIES.ch02_official_robes_walk.dialogues.every(x=>['thought','narration'].includes(x.speakerType)));assert.equal(STORIES.ch02_hyunwoo_official.enterCharacterStates.hyunwoo.outfit,'young_official');
assert.equal(STORIES.ch03_policy_choice.choices.length,3);assert(STORIES.ch03_policy_choice.choices.every(c=>c.importantChoice));assert.equal(STORIES.ch03_transition.sceneEffect,'blackout');assert.equal(STORIES.ch03_transition.dialogues.at(-1).dialogue,'982년 — 개경');assert(STORIES.ch03_unchanged.dialogues.some(line=>line.speakerType==='thought'&&line.dialogue.includes('언제까지')));assert(STORIES.ch03_farewell.dialogues.some(line=>line.dialogue.includes('얼마나 더 살아야')));assert(STORIES.ch03_legacy.completeChapter);assert.equal(QUESTIONS.find(q=>q.questionId==='ch03-official-75-basic-10').answer,2);assert(QUESTIONS.filter(q=>q.chapterId==='ch04'&&!q.isOfficial).every(q=>['한능검 기출 유형','실전 유형 연습'].some(label=>q.examType.includes(label))));
assert.equal(CHARACTER_ASSET_MAP.doyun.ages.elder_982.outfits.guild_master.neutral,'doyun_old_neutral');assert.equal(CHARACTER_ASSET_MAP.hyunwoo.ages.middle_982.outfits.official_scholar.thinking,'hyunwoo_middle_thinking');
for(const name of ['doyun_old_neutral','doyun_old_smile','doyun_old_laugh','doyun_old_serious','doyun_old_tired','doyun_old_sad','doyun_old_weak_smile','hyunwoo_middle_neutral','hyunwoo_middle_smile','hyunwoo_middle_serious','hyunwoo_middle_thinking']){assert.equal(PORTRAITS[name].status,'ready');assert(fs.existsSync('dist/'+PORTRAITS[name].src),`${name}: missing generated portrait`)}
for(const[id,asset]of Object.entries(ASSETS))if(asset.src)assert(fs.existsSync('dist/'+asset.src),`${id}: missing generated scene file ${asset.src}`);
for(const expression of ['neutral','smile','surprised','worried','thinking','serious','embarrassed','angry','sad'])assert(fs.existsSync('dist/'+PORTRAITS[`player_${expression}`].src));
for(const expression of ['neutral','smile','surprised','worried','thinking','serious','embarrassed'])assert(fs.existsSync('dist/'+PORTRAITS[`player_goryeo_${expression}`].src));
for(const expression of ['neutral','smile','surprised','suspicious','serious','worried'])assert(fs.existsSync('dist/'+PORTRAITS[`doyun_${expression}`].src));
for(const expression of ['neutral','worried','smile']){const p=PORTRAITS[`hyunwoo_${expression}`];assert.equal(p.status,'ready');assert(fs.existsSync('dist/'+p.src));}
assert.equal(CHARACTER_ASSET_MAP.doyun.canonicalId,'DOYUN_CANONICAL');
for(const expression of ['neutral','smile','surprised','suspicious','serious','worried'])assert.equal(CHARACTER_ASSET_MAP.doyun.ages.young.outfits.commoner[expression],`doyun_${expression}`);
for(const expression of ['neutral','smile','surprised','serious','worried']){assert.equal(CHARACTER_ASSET_MAP.doyun.ages.middle_aged_949.outfits.shop_owner[expression],`doyun_949_${expression}`);assert.equal(CHARACTER_ASSET_MAP.doyun.ages.elder_956.outfits.established_merchant[expression],`doyun_956_${expression}`);assert(fs.existsSync(`dist/assets/characters/doyun_949_${expression}.png`));assert(fs.existsSync(`dist/assets/characters/doyun_956_${expression}.png`));}
assert(STORIES.house.dialogues.filter(line=>line.speakerType==='npc').every(line=>line.characterId==='doyun'&&line.portrait.startsWith('doyun_')));
assert(STORIES.house.dialogues.some(line=>line.characterName==='낯선 청년'));
const expectedSceneSources={
  'goryeo-house':'assets/scenes/goryeo-house-empty.png','goryeo-house-question':'assets/scenes/goryeo-house-empty.png',
  'village-reveal':'assets/scenes/route-village.png','village-rumor':'assets/scenes/village-residents-rumor-918.png',
  'memory-wanggeon':'assets/scenes/title-foundation.png','market-later-three-kingdoms':'assets/scenes/market-rumors-918.png',
  'route-songak-carry':'assets/scenes/route-songak.png','route-songak-talk':'assets/scenes/route-songak.png',
  'route-village-help':'assets/scenes/route-village.png','route-village-call':'assets/scenes/route-village.png','route-village-leave':'assets/scenes/route-village.png',
  'route-caravan-work':'assets/scenes/route-caravan.png','route-caravan-negotiate':'assets/scenes/route-caravan.png','route-caravan-goods':'assets/scenes/route-caravan.png',
  'thief-chase':'assets/scenes/thief-start.png','thief-block':'assets/scenes/thief-start.png','thief-alley':'assets/scenes/thief-start.png','thief-ignore':'assets/scenes/thief-aftermath.png',
  'first-night':'assets/scenes/first-night-goryeo.png','future-flow':'assets/scenes/title-foundation.png','chapter-complete':'assets/scenes/route-songak.png',
  'ch02-reign-titles':'assets/scenes/ch02-official-robes-street-960.png'
};
for(const[id,src]of Object.entries(expectedSceneSources))assert.equal(ASSETS[id].src,src,`${id}: audited source mismatch`);
for(const id of Object.keys(expectedSceneSources).filter(id=>!['first-night','village-rumor','market-later-three-kingdoms','ch02-reign-titles'].includes(id)))assert.equal(ASSETS[id].embeddedCharacters,false,`${id}: sprites must own character continuity`);
for(const id of ['village-rumor','market-later-three-kingdoms','ch02-reign-titles'])assert.equal(ASSETS[id].embeddedCharacters,true,`${id}: anonymous people must be embedded in the scene illustration`);
assert.deepEqual(Array.from(ASSETS['first-night'].embeddedCharacterIds),['player']);

const outfitMilestone=INITIAL();outfitMilestone.run.started=true;outfitMilestone.run.storyId='outfit_gift';applySceneEntry(outfitMilestone,'outfit_gift');
assert.equal(outfitMilestone.run.playerOutfit,'modern');applyDialogueMilestone(outfitMilestone,'outfit_gift',7);assert.equal(outfitMilestone.run.playerOutfit,'modern');
applyDialogueMilestone(outfitMilestone,'outfit_gift',8);assert.equal(outfitMilestone.run.playerOutfit,'goryeo_commoner');assert.equal(outfitMilestone.run.flags.wearingModernClothes,false);assert(outfitMilestone.run.flags.hasModernClothes);assert(outfitMilestone.run.inventory.some(item=>item.id==='modern-clothes'&&item.status==='stored'));assert(outfitMilestone.run.inventory.some(item=>item.id==='goryeo-commoner-clothes'&&item.status==='equipped'));

function walk(startId,state,endId){let paths=0;const tests=new Set(),branches=new Set(),choices=new Set();
  function visit(id,copy,stack=[]){assert(!stack.includes(id),`cycle: ${[...stack,id].join(' -> ')}`);if(id===endId){paths++;return}const s=STORIES[id];assert(s,`missing scene ${id}`);applySceneEntry(copy,id);applyDialogueMilestone(copy,id,s.dialogues.length);
    if(s.completeChapter){paths++;return}
    if(s.questionSetId&&QUESTION_SETS[s.questionSetId]?.status==='ready'){const set=QUESTION_SETS[s.questionSetId];for(const qid of [...(set.officialQuestionIds||[]),...(set.practiceQuestionIds||[])]){const q=QUESTIONS.find(x=>x.questionId===qid&&!x.retired);tests.add(q.questionId);recordQuestion(copy,q.questionId,q.answer)}copy.run.activeQuestionId=null;copy.run.questionAnswer=null;return visit(set.resumeStoryId,copy,[...stack,id])}
    if(s.questionSequenceMode==='queue'&&s.linkedQuestionIds?.length){let resume=s.nextStoryId;for(const qid of s.linkedQuestionIds){const q=QUESTIONS.find(x=>x.questionId===qid&&!x.retired);tests.add(q.questionId);recordQuestion(copy,q.questionId,q.answer);resume=q.resumeStoryId}copy.run.activeQuestionId=null;copy.run.questionAnswer=null;return visit(resume,copy,[...stack,id])}
    if(s.quizId){const q=QUESTIONS.find(x=>x.questionId===s.quizId);tests.add(q.questionId);recordQuestion(copy,q.questionId,q.answer);copy.run.activeQuestionId=null;copy.run.questionAnswer=null;return visit(q.resumeStoryId,copy,[...stack,id])}
    if(s.choices){branches.add(id);s.choices.forEach((c,i)=>{choices.add(`${id}:${i}`);const next=JSON.parse(JSON.stringify(copy));if(!choiceAvailable(next.run,c))return;applyChoice(next,id,i);next.run.pending=null;visit(next.run.storyId,next,[...stack,id])});return}
    assert(s.nextStoryId,`${id}: dead end`);visit(s.nextStoryId,copy,[...stack,id]);
  }visit(startId,state);return{paths,tests,branches,choices};}
const ch1=INITIAL();ch1.run.started=true;const ch1Coverage=walk('prologue',ch1,'complete');assert.equal(ch1Coverage.paths,4);assert.equal(ch1Coverage.tests.size,2);
const carry=INITIAL();carry.run.started=true;carry.run.stats={health:83,knowledge:9,fame:7,wealth:22};carry.run.relations.doyun=17;carry.run.job='상단 장부 보조';finishChapter(carry);
assert(carry.meta.completedChapters.includes('ch01'));assert(carry.meta.chapterRecords.ch01);startChapter(carry,'ch02');finishChapter(carry);assert(startChapter(carry,'ch03'));assert.equal(carry.run.storyId,'ch02_transition');assert.equal(carry.run.stats.wealth,22);assert.equal(carry.run.job,'상단 장부 보조');assert.equal(carry.run.relations.doyun,17);assert.equal(carry.run.playerOutfit,'goryeo_commoner');
assert.equal(carry.run.characterStates.doyun.ageVariant,'middle_aged_949');assert.equal(carry.run.characterStates.doyun.characterAge,55);
const ch2Coverage=walk('ch02_transition',JSON.parse(JSON.stringify(carry)),null);assert.equal(ch2Coverage.paths,324);assert.equal(ch2Coverage.tests.size,3);assert.equal(ch2Coverage.branches.size,5);assert.equal(ch2Coverage.choices.size,16);
const ch3State=INITIAL();ch3State.run.started=true;finishChapter(ch3State);startChapter(ch3State,'ch02');finishChapter(ch3State);assert(startChapter(ch3State,'ch03'));finishChapter(ch3State);assert(startChapter(ch3State,'ch04'));assert.equal(ch3State.run.storyId,'ch03_transition');assert.equal(ch3State.run.playerOutfit,'goryeo_commoner');assert.equal(ch3State.run.characterStates.doyun.ageVariant,'elder_982');assert.equal(ch3State.run.characterStates.doyun.characterAge,88);assert.equal(ch3State.run.characterStates.hyunwoo.ageVariant,'middle_982');assert.equal(ch3State.run.characterStates.hyunwoo.characterAge,47);assert.equal(ch3State.run.doyunLegacy.name,'도윤상단');
const ch3Coverage=walk('ch03_transition',JSON.parse(JSON.stringify(ch3State)),null);assert.equal(ch3Coverage.paths,3);assert.equal(ch3Coverage.tests.size,3);assert.equal(ch3Coverage.branches.size,1);assert.equal(ch3Coverage.choices.size,3);
applySceneEntry(ch3State,'ch03_seongjong_news');applySceneEntry(ch3State,'ch03_choe_reform');applySceneEntry(ch3State,'ch03_twelve_mok');applySceneEntry(ch3State,'ch03_gukjagam');assert(ch3State.meta.people.includes('성종')&&ch3State.meta.people.includes('최승로'));assert(ch3State.meta.cards.includes('gukjagam')&&ch3State.meta.cards.includes('simu-28'));
applySceneEntry(ch3State,'ch03_death');applySceneEntry(ch3State,'ch03_legacy');assert.equal(ch3State.run.characterStates.doyun.isAlive,false);finishChapter(ch3State);assert(ch3State.meta.completedChapters.includes('ch04'));assert.equal(ch3State.run.doyunLegacy.merchantGuild,true);assert.equal(ch3State.run.doyunLegacy.name,'도윤상단');assert.equal(ch3State.run.characterStates.doyun.deathCause,'old_age');
const ch3MainBeforeReplay=JSON.parse(JSON.stringify(ch3State.run)),ch3Official='ch03-official-75-basic-10',ch3AttemptsBefore=ch3State.meta.questionRecords[ch3Official]?.attempts||0;assert(beginReplay(ch3State,'ch04'));assert.equal(ch3State.run.mode,'replay');assert.equal(ch3State.run.storyId,'ch03_transition');recordQuestion(ch3State,ch3Official,QUESTIONS.find(q=>q.questionId===ch3Official).answer);applySceneEntry(ch3State,'ch03_death');applySceneEntry(ch3State,'ch03_legacy');finishChapter(ch3State);assert.equal(ch3State.meta.chapterRuns.ch04.length,2);assert.equal(ch3State.meta.questionRecords[ch3Official].attempts,ch3AttemptsBefore+1);assert(ch3State.meta.completedChapters.includes('ch01')&&ch3State.meta.completedChapters.includes('ch03')&&ch3State.meta.completedChapters.includes('ch04'));assert(restoreMainRun(ch3State));assert.deepEqual(ch3State.run,ch3MainBeforeReplay);
applyChoice(carry,'ch02_market',0);carry.run.pending=null;carry.run.stats.wealth=99;restartChapter(carry);assert.equal(carry.run.currentChapter,'ch03');assert.equal(carry.run.storyId,'ch02_transition');assert.equal(carry.run.stats.wealth,22);assert.equal(carry.run.job,'상단 장부 보조');assert(carry.meta.completedChapters.includes('ch01'));
recordQuestion(carry,'ch02-test-01',QUESTIONS.find(q=>q.questionId==='ch02-test-01').answer);carry.run.storyId='ch02_complete';finishChapter(carry);assert(carry.meta.completedChapters.includes('ch03'));assert(carry.meta.chapterRecords.ch03);assert(carry.meta.chapterRuns.ch03.length===1);assert(carry.meta.cards.includes('gwangjong-authority'));assert(carry.meta.people.includes('쌍기'));
const mainBeforeReplay=JSON.parse(JSON.stringify(carry.run)),attemptsBefore=carry.meta.questionRecords['ch02-test-01'].attempts;assert(beginReplay(carry,'ch01'));assert.equal(carry.run.mode,'replay');assert.equal(carry.run.storyId,'prologue');assert.deepEqual(carry.mainRun,mainBeforeReplay);recordQuestion(carry,'ch01-test-01',QUESTIONS.find(q=>q.questionId==='ch01-test-01').answer);finishChapter(carry);assert.equal(carry.meta.chapterRuns.ch01.length,2);assert.equal(carry.meta.chapterRecords.ch01.firstRun.runId,1);assert.equal(carry.meta.chapterRecords.ch01.latestRun.runId,2);assert(carry.meta.completedChapters.includes('ch03'));assert.equal(carry.meta.questionRecords['ch02-test-01'].attempts,attemptsBefore);assert(restoreMainRun(carry));assert.deepEqual(carry.run,mainBeforeReplay);
const scoreRuns=INITIAL(),ch02Questions=QUESTIONS.filter(q=>q.chapterId==='ch03'&&!q.reviewOnly&&!q.retired);scoreRuns.run.started=true;finishChapter(scoreRuns);startChapter(scoreRuns,'ch02');finishChapter(scoreRuns);startChapter(scoreRuns,'ch03');for(const [index,q] of ch02Questions.entries())recordQuestion(scoreRuns,q.questionId,index<3?q.answer:(q.answer+1)%q.choices.length);finishChapter(scoreRuns);assert(beginReplay(scoreRuns,'ch03'));for(const q of ch02Questions)recordQuestion(scoreRuns,q.questionId,q.answer);finishChapter(scoreRuns);assert.equal(scoreRuns.meta.chapterRuns.ch03.length,2);assert.equal(scoreRuns.meta.chapterRecords.ch03.firstRun.questionScore.correct,3);assert.equal(scoreRuns.meta.chapterRecords.ch03.latestRun.questionScore.correct,3);assert.equal(scoreRuns.meta.chapterRecords.ch03.bestQuestionScore,3);
const legacy=INITIAL();legacy.version=3;legacy.run.started=true;legacy.run.completed=true;legacy.run.storyId='complete';legacy.run.stats.wealth=30;legacy.meta.cards.push('legacy-card');delete legacy.run.currentChapter;delete legacy.meta.completedChapters;delete legacy.meta.chapterRecords;
const migrated=migrateSave(legacy);assert.equal(migrated.version,15);assert(migrated.meta.completedChapters.includes('ch01'));assert(migrated.meta.chapterRecords.ch01);assert.equal(migrated.meta.chapterRuns.ch01.length,1);assert.equal(migrated.run.stats.wealth,30);assert.equal(migrated.run.playerOutfit,'goryeo_commoner');assert.equal(migrated.run.flags.wearingModernClothes,false);assert(migrated.run.flags.hasModernClothes);
const midChapter=INITIAL();midChapter.version=4;midChapter.run.started=true;midChapter.run.storyId='village';const migratedMid=migrateSave(midChapter);assert.equal(migratedMid.run.playerOutfit,'goryeo_commoner');assert.equal(migratedMid.run.flags.wearingModernClothes,false);assert(migratedMid.run.inventory.some(item=>item.id==='modern-clothes'&&item.status==='stored'));assert(migratedMid.run.inventory.some(item=>item.id==='goryeo-commoner-clothes'&&item.status==='equipped'));
const pendingHouse=INITIAL();pendingHouse.version=4;pendingHouse.run.started=true;pendingHouse.run.storyId='village';pendingHouse.run.pending={sourceSceneId:'house',nextStoryId:'village'};const migratedPending=migrateSave(pendingHouse);assert.equal(migratedPending.run.storyId,'outfit_gift');assert.equal(migratedPending.run.pending,null);assert.equal(migratedPending.run.flags.wearingModernClothes,true);
const earlyGiftV6=INITIAL();earlyGiftV6.version=6;earlyGiftV6.run.started=true;earlyGiftV6.run.storyId='outfit_gift';earlyGiftV6.run.dialogueCursor=3;earlyGiftV6.run.flags.wearingModernClothes=false;earlyGiftV6.run.flags.receivedGoryeoClothesFromDoyun=true;earlyGiftV6.run.inventory.push({id:'goryeo-commoner-clothes',status:'equipped',source:'doyun'});const repairedEarlyGift=migrateSave(earlyGiftV6);assert.equal(repairedEarlyGift.run.playerOutfit,'modern');assert.equal(repairedEarlyGift.run.flags.receivedGoryeoClothesFromDoyun,false);assert(!repairedEarlyGift.run.inventory.some(item=>item.id==='goryeo-commoner-clothes'));
const brokenV6=INITIAL();brokenV6.version=6;brokenV6.run.started=true;brokenV6.run.storyId='village';brokenV6.run.playerOutfit='modern';brokenV6.run.flags.wearingModernClothes=true;const repairedV6=migrateSave(brokenV6);assert.equal(repairedV6.run.playerOutfit,'goryeo_commoner');assert.equal(repairedV6.run.flags.wearingModernClothes,false);
const replayV6=INITIAL();replayV6.version=6;replayV6.meta.completedChapters.push('ch01');replayV6.run.started=true;replayV6.run.mode='replay';replayV6.run.replayChapterId='ch01';replayV6.run.storyId='prologue';const repairedReplay=migrateSave(replayV6);assert.equal(repairedReplay.run.playerOutfit,'modern');assert.equal(repairedReplay.run.flags.wearingModernClothes,true);
const mysterySave=INITIAL();mysterySave.version=5;mysterySave.run.started=true;mysterySave.run.currentChapter='ch03';mysterySave.run.storyId='ch02_reflection';mysterySave.run.sharedEvents.push('noticed_unchanged_appearance');mysterySave.meta.mysteries.push('unknown-aging');mysterySave.meta.knowledgeMemory['unknown-aging']={title:'???'};const migratedMystery=migrateSave(mysterySave);assert.equal(migratedMystery.run.storyId,'ch02_purge');assert(!migratedMystery.run.sharedEvents.includes('noticed_unchanged_appearance'));assert(!migratedMystery.meta.mysteries.includes('unknown-aging'));assert(!migratedMystery.meta.knowledgeMemory['unknown-aging']);
const currentMystery=INITIAL();currentMystery.run.started=true;currentMystery.run.currentChapter='ch03';currentMystery.run.storyId='ch02_mystery';applySceneEntry(currentMystery,'ch02_mystery');const migratedCurrentMystery=migrateSave(currentMystery);assert(migratedCurrentMystery.meta.mysteries.includes('unknown-aging'));assert(migratedCurrentMystery.meta.knowledgeMemory['unknown-aging']);assert(migratedCurrentMystery.run.sharedEvents.includes('noticed_unchanged_appearance'));
const unfinishedCh03V10=INITIAL();unfinishedCh03V10.version=10;unfinishedCh03V10.ch03StoryVersion=1;unfinishedCh03V10.run.started=true;unfinishedCh03V10.run.currentChapter='ch03';unfinishedCh03V10.run.storyId='ch02_purge';unfinishedCh03V10.run.activeQuestionId='ch02-test-05';unfinishedCh03V10.run.questionAnswer=0;const migratedUnfinishedCh03=migrateSave(unfinishedCh03V10);assert.equal(migratedUnfinishedCh03.version,15);assert.equal(migratedUnfinishedCh03.ch03StoryVersion,2);assert.equal(migratedUnfinishedCh03.run.storyId,'ch02_official_robes_walk');assert.equal(migratedUnfinishedCh03.run.activeQuestionId,null);assert.equal(migratedUnfinishedCh03.run.questionAnswer,null);assert.equal(migratedUnfinishedCh03.run.completed,false);
const completedCh03V10=INITIAL();completedCh03V10.version=10;completedCh03V10.ch03StoryVersion=1;completedCh03V10.run.started=true;completedCh03V10.run.currentChapter='ch03';completedCh03V10.run.storyId='ch02_mystery';completedCh03V10.run.completed=true;completedCh03V10.meta.completedChapters.push('ch03');const migratedCompletedCh03=migrateSave(completedCh03V10);assert.equal(migratedCompletedCh03.version,15);assert.equal(migratedCompletedCh03.ch03StoryVersion,2);assert.equal(migratedCompletedCh03.run.storyId,'ch02_mystery');assert.equal(migratedCompletedCh03.run.completed,true);assert(migratedCompletedCh03.meta.completedChapters.includes('ch03'));
const manifest=fs.readFileSync('docs/CHARACTER_ASSET_REQUIRED.md','utf8');for(const id of Object.keys(PORTRAITS).filter(id=>PORTRAITS[id].status==='ASSET_REQUIRED'))assert(manifest.includes('`'+id+'`'),`required portrait manifest missing ${id}`);
console.log(JSON.stringify({scenes:Object.keys(STORIES).length,ch01Scenes:Object.values(STORIES).filter(s=>s.chapterId==='ch01').length,ch02Scenes:Object.values(STORIES).filter(s=>s.chapterId==='ch03').length,questions:QUESTIONS.length,ch02Paths:ch2Coverage.paths,ch02Choices:ch2Coverage.choices.size,status:'PASS'}));
