const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const code=fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/ch02-data.js','utf8');
const ctx=vm.createContext({Date});
vm.runInContext(code+';this.api={SAVE_VERSION,CHAPTERS,STORIES,QUESTIONS,ASSETS,EXPRESSIONS,PORTRAITS,CHARACTERS,CHARACTER_ASSET_MAP,INITIAL,INITIAL_RUN,applyChoice,applySceneEntry,applyDialogueMilestone,choiceAvailable,recordQuestion,finishChapter,resetRun,setPlayerOutfit,startChapter,restartChapter,beginReplay,restoreMainRun,migrateSave};',ctx);
const{SAVE_VERSION,CHAPTERS,STORIES,QUESTIONS,ASSETS,EXPRESSIONS,PORTRAITS,CHARACTER_ASSET_MAP,INITIAL,applyChoice,applySceneEntry,applyDialogueMilestone,choiceAvailable,recordQuestion,finishChapter,startChapter,restartChapter,beginReplay,restoreMainRun,migrateSave}=ctx.api;
assert.equal(SAVE_VERSION,8);
assert.equal(Object.keys(CHAPTERS).length,11);assert(CHAPTERS.ch01.implemented&&CHAPTERS.ch02.implemented);assert(!CHAPTERS.ch03.implemented);assert.equal(CHAPTERS.ch11.title,'고려의 마지막 날');
assert.equal(QUESTIONS.filter(q=>q.chapterId==='ch01').length,6,'CH.01 must retain six tests');
assert.equal(QUESTIONS.filter(q=>q.chapterId==='ch02').length,5,'CH.02 must have five distributed tests');
const protectedQuestionFields=['questionId','passage','question','choices','answer','explanation','examKeywords','relatedSceneId','resumeStoryId'];
const protectedCh02Questions=QUESTIONS.filter(q=>q.chapterId==='ch02').map(q=>Object.fromEntries(protectedQuestionFields.map(field=>[field,q[field]])));
assert.equal(crypto.createHash('sha256').update(JSON.stringify(protectedCh02Questions)).digest('hex'),'b4736a63af74f23f009e9d1e6dfa9821a3c60016813efa16609b6711c47741c3','CH.02 protected problem data changed');
const requiredQuestionFields=['questionId','chapterId','relatedSceneId','relatedHistoricalEventId','relatedIllustrationId','questionType','difficulty','passage','question','choices','answer','explanation','examKeywords','userAnswer','isCorrect','isOfficial','source','examRound','examYear','questionNumber'];
for(const q of QUESTIONS){
  for(const field of requiredQuestionFields)assert(Object.prototype.hasOwnProperty.call(q,field),`${q.questionId}: missing ${field}`);
  assert(q.answer>=0&&q.answer<q.choices.length,`${q.questionId}: invalid answer`);
  assert.equal(q.isOfficial,false,`${q.questionId}: copied official content is not allowed`);
  assert(STORIES[q.relatedSceneId],`${q.questionId}: missing related scene`);
  assert(ASSETS[q.relatedIllustrationId],`${q.questionId}: missing related illustration`);
  assert(STORIES[q.resumeStoryId],`${q.questionId}: missing resume scene`);
}
for(const[id,s]of Object.entries(STORIES)){
  assert.equal(s.sceneId,id,`${id}: sceneId mismatch`);assert(ASSETS[s.illustrationId],`${id}: missing illustration`);
  if(s.nextStoryId)assert(STORIES[s.nextStoryId],`${id}: missing next scene ${s.nextStoryId}`);
  if(s.quizId)assert(QUESTIONS.some(q=>q.questionId===s.quizId),`${id}: missing quiz ${s.quizId}`);
  assert(Array.isArray(s.dialogues)&&s.dialogues.length,`${id}: structured dialogues required`);
  for(const line of s.dialogues){
    for(const field of ['characterId','characterName','speakerType','portrait','expression','dialogue','alignment'])assert(Object.prototype.hasOwnProperty.call(line,field),`${id}: dialogue missing ${field}`);
    assert(['player','npc','thought','narration'].includes(line.speakerType),`${id}: unsupported speaker type`);assert(EXPRESSIONS.includes(line.expression),`${id}: unsupported expression ${line.expression}`);
    assert.equal(line.alignment,line.speakerType==='player'?'right':line.speakerType==='npc'?'left':'center',`${id}: alignment must derive from speakerType`);
    if(['player','npc'].includes(line.speakerType))assert(PORTRAITS[line.portrait],`${id}: missing portrait ${line.portrait}`);
  }
  for(const c of s.choices||[]){assert(STORIES[c.nextStoryId],`${id}: missing choice destination`);assert(c.resultSceneId&&ASSETS[c.resultIllustrationId],`${id}: result scene/illustration required`);assert(Array.isArray(c.resultDialogues)&&c.resultDialogues.length>=2,`${id}: player response and reaction required`);assert.equal(c.resultDialogues[0].speakerType,'player');}
}
assert.deepEqual(STORIES.status.dialogues.map(x=>x.speakerType),['npc','player','npc','player','thought']);
assert.equal(STORIES.voice.sceneEffect,'blackout');assert.equal(STORIES.voice.autoAdvanceDelays.length,4);assert.equal(STORIES.voice.dialogues.length,5);
assert.equal(STORIES.outfit_question.choices.length,4);assert.equal(STORIES.outfit_gift.outfitChange.dialogueIndex,7);assert.equal(STORIES.outfit_gift.outfitChange.to,'goryeo_commoner');assert(!STORIES.outfit_gift.enterFlags);
assert.equal(STORIES.life_choice.choices.length,4);assert.equal(STORIES.ch02_market.choices.length,4);assert.equal(STORIES.ch02_life_path.choices.length,3);assert.equal(STORIES.ch02_trust.choices.length,3);assert(STORIES.ch02_trust.choices.every(c=>c.importantChoice));assert.equal(STORIES.ch02_policy_reason.choices[0].memoryKey,'ch02-nobi-purpose');assert(STORIES.ch02_exam_notice.dialogues.some(x=>x.characterId==='hyunwoo'));assert(STORIES.ch02_three_way.dialogues.some(x=>x.characterId==='doyun'));assert(!STORIES.ch02_unchanged);assert(!STORIES.ch02_reflection);assert(!ASSETS['ch02-reflection']);assert(STORIES.ch02_night_reflection);assert(STORIES.ch02_mystery.mysteryKey==='unknown-aging'&&STORIES.ch02_mystery.completeChapter);assert.equal(QUESTIONS.find(q=>q.questionId==='ch02-test-04').resumeStoryId,'ch02_purge');assert(STORIES.ch02_purge.dialogues.some(x=>x.speakerType==='thought'));
for(const[id,asset]of Object.entries(ASSETS))if(asset.src)assert(fs.existsSync('dist/'+asset.src),`${id}: missing generated scene file ${asset.src}`);
for(const expression of ['neutral','smile','surprised','worried','thinking','serious','embarrassed','angry','sad'])assert(fs.existsSync('dist/'+PORTRAITS[`player_${expression}`].src));
for(const expression of ['neutral','smile','surprised','worried','thinking','serious','embarrassed'])assert(fs.existsSync('dist/'+PORTRAITS[`player_goryeo_${expression}`].src));
for(const expression of ['neutral','smile','surprised','suspicious','serious','worried'])assert(fs.existsSync('dist/'+PORTRAITS[`doyun_${expression}`].src));
for(const expression of ['neutral','worried','smile']){const p=PORTRAITS[`hyunwoo_${expression}`];assert.equal(p.status,'ready');assert(fs.existsSync('dist/'+p.src));}
assert.equal(CHARACTER_ASSET_MAP.doyun.canonicalId,'DOYUN_CANONICAL');
for(const expression of ['neutral','smile','surprised','suspicious','serious','worried'])assert.equal(CHARACTER_ASSET_MAP.doyun.ages.young.outfits.commoner[expression],`doyun_${expression}`);
for(const expression of ['neutral','smile','surprised','serious','worried']){assert.equal(CHARACTER_ASSET_MAP.doyun.ages.middle_aged_949.outfits.shop_owner[expression],`doyun_949_${expression}`);assert.equal(CHARACTER_ASSET_MAP.doyun.ages.elder_956.outfits.established_merchant[expression],`doyun_956_${expression}`);assert(fs.existsSync(`dist/assets/characters/doyun_949_${expression}.png`));assert(fs.existsSync(`dist/assets/characters/doyun_956_${expression}.png`));}
assert(STORIES.house.dialogues.filter(line=>line.speakerType==='npc').every(line=>line.characterId==='doyun'&&line.portrait.startsWith('doyun_')));
assert(STORIES.house.dialogues.some(line=>line.characterName==='낯선 청년'));
const expectedSceneSources={
  'goryeo-house':'assets/scenes/goryeo-house-empty.png','goryeo-house-question':'assets/scenes/goryeo-house-empty.png',
  'village-reveal':'assets/scenes/route-village.png','village-rumor':'assets/scenes/status-first.png',
  'memory-wanggeon':'assets/scenes/title-foundation.png','market-later-three-kingdoms':'assets/scenes/doyun-intro.png',
  'route-songak-carry':'assets/scenes/route-songak.png','route-songak-talk':'assets/scenes/route-songak.png',
  'route-village-help':'assets/scenes/route-village.png','route-village-call':'assets/scenes/route-village.png','route-village-leave':'assets/scenes/route-village.png',
  'route-caravan-work':'assets/scenes/route-caravan.png','route-caravan-negotiate':'assets/scenes/route-caravan.png','route-caravan-goods':'assets/scenes/route-caravan.png',
  'thief-chase':'assets/scenes/thief-start.png','thief-block':'assets/scenes/thief-start.png','thief-alley':'assets/scenes/thief-start.png','thief-ignore':'assets/scenes/thief-aftermath.png',
  'first-night':'assets/scenes/first-night-goryeo.png','future-flow':'assets/scenes/title-foundation.png','chapter-complete':'assets/scenes/route-songak.png'
};
for(const[id,src]of Object.entries(expectedSceneSources))assert.equal(ASSETS[id].src,src,`${id}: audited source mismatch`);
for(const id of Object.keys(expectedSceneSources).filter(id=>id!=='first-night'))assert.equal(ASSETS[id].embeddedCharacters,false,`${id}: sprites must own character continuity`);
assert.deepEqual(Array.from(ASSETS['first-night'].embeddedCharacterIds),['player']);

const outfitMilestone=INITIAL();outfitMilestone.run.started=true;outfitMilestone.run.storyId='outfit_gift';applySceneEntry(outfitMilestone,'outfit_gift');
assert.equal(outfitMilestone.run.playerOutfit,'modern');applyDialogueMilestone(outfitMilestone,'outfit_gift',6);assert.equal(outfitMilestone.run.playerOutfit,'modern');
applyDialogueMilestone(outfitMilestone,'outfit_gift',7);assert.equal(outfitMilestone.run.playerOutfit,'goryeo_commoner');assert.equal(outfitMilestone.run.flags.wearingModernClothes,false);assert(outfitMilestone.run.flags.hasModernClothes);assert(outfitMilestone.run.inventory.some(item=>item.id==='modern-clothes'&&item.status==='stored'));assert(outfitMilestone.run.inventory.some(item=>item.id==='goryeo-commoner-clothes'&&item.status==='equipped'));

function walk(startId,state,endId){let paths=0;const tests=new Set(),branches=new Set(),choices=new Set();
  function visit(id,copy,stack=[]){assert(!stack.includes(id),`cycle: ${[...stack,id].join(' -> ')}`);if(id===endId){paths++;return}const s=STORIES[id];assert(s,`missing scene ${id}`);applySceneEntry(copy,id);applyDialogueMilestone(copy,id,s.dialogues.length);
    if(s.completeChapter){paths++;return}
    if(s.quizId){const q=QUESTIONS.find(x=>x.questionId===s.quizId);tests.add(q.questionId);recordQuestion(copy,q.questionId,q.answer);copy.run.activeQuestionId=null;copy.run.questionAnswer=null;return visit(q.resumeStoryId,copy,[...stack,id])}
    if(s.choices){branches.add(id);s.choices.forEach((c,i)=>{choices.add(`${id}:${i}`);const next=JSON.parse(JSON.stringify(copy));if(!choiceAvailable(next.run,c))return;applyChoice(next,id,i);next.run.pending=null;visit(next.run.storyId,next,[...stack,id])});return}
    assert(s.nextStoryId,`${id}: dead end`);visit(s.nextStoryId,copy,[...stack,id]);
  }visit(startId,state);return{paths,tests,branches,choices};}
const ch1=INITIAL();ch1.run.started=true;const ch1Coverage=walk('prologue',ch1,'complete');assert(ch1Coverage.paths>=20);assert.equal(ch1Coverage.tests.size,6);
const carry=INITIAL();carry.run.started=true;carry.run.stats={health:83,knowledge:9,fame:7,wealth:22};carry.run.relations.doyun=17;carry.run.job='상단 장부 보조';finishChapter(carry);
assert(carry.meta.completedChapters.includes('ch01'));assert(carry.meta.chapterRecords.ch01);assert(startChapter(carry,'ch02'));assert.equal(carry.run.storyId,'ch02_transition');assert.equal(carry.run.stats.wealth,22);assert.equal(carry.run.job,'상단 장부 보조');assert.equal(carry.run.relations.doyun,17);assert.equal(carry.run.playerOutfit,'goryeo_commoner');
assert.equal(carry.run.characterStates.doyun.ageVariant,'middle_aged_949');assert.equal(carry.run.characterStates.doyun.characterAge,57);
const ch2Coverage=walk('ch02_transition',JSON.parse(JSON.stringify(carry)),null);assert.equal(ch2Coverage.paths,324);assert.equal(ch2Coverage.tests.size,5);assert.equal(ch2Coverage.branches.size,5);assert.equal(ch2Coverage.choices.size,16);
applyChoice(carry,'ch02_market',0);carry.run.pending=null;carry.run.stats.wealth=99;restartChapter(carry);assert.equal(carry.run.currentChapter,'ch02');assert.equal(carry.run.storyId,'ch02_transition');assert.equal(carry.run.stats.wealth,22);assert.equal(carry.run.job,'상단 장부 보조');assert(carry.meta.completedChapters.includes('ch01'));
recordQuestion(carry,'ch02-test-01',QUESTIONS.find(q=>q.questionId==='ch02-test-01').answer);carry.run.storyId='ch02_complete';finishChapter(carry);assert(carry.meta.completedChapters.includes('ch02'));assert(carry.meta.chapterRecords.ch02);assert(carry.meta.chapterRuns.ch02.length===1);assert(carry.meta.cards.includes('gwangjong-authority'));assert(carry.meta.people.includes('쌍기'));
const mainBeforeReplay=JSON.parse(JSON.stringify(carry.run)),attemptsBefore=carry.meta.questionRecords['ch02-test-01'].attempts;assert(beginReplay(carry,'ch01'));assert.equal(carry.run.mode,'replay');assert.equal(carry.run.storyId,'prologue');assert.deepEqual(carry.mainRun,mainBeforeReplay);recordQuestion(carry,'ch01-test-01',QUESTIONS.find(q=>q.questionId==='ch01-test-01').answer);finishChapter(carry);assert.equal(carry.meta.chapterRuns.ch01.length,2);assert.equal(carry.meta.chapterRecords.ch01.firstRun.runId,1);assert.equal(carry.meta.chapterRecords.ch01.latestRun.runId,2);assert(carry.meta.completedChapters.includes('ch02'));assert.equal(carry.meta.questionRecords['ch02-test-01'].attempts,attemptsBefore);assert(restoreMainRun(carry));assert.deepEqual(carry.run,mainBeforeReplay);
const scoreRuns=INITIAL(),ch02Questions=QUESTIONS.filter(q=>q.chapterId==='ch02');scoreRuns.run.started=true;finishChapter(scoreRuns);startChapter(scoreRuns,'ch02');for(const [index,q] of ch02Questions.entries())recordQuestion(scoreRuns,q.questionId,index<3?q.answer:(q.answer+1)%q.choices.length);finishChapter(scoreRuns);assert(beginReplay(scoreRuns,'ch02'));for(const q of ch02Questions)recordQuestion(scoreRuns,q.questionId,q.answer);finishChapter(scoreRuns);assert.equal(scoreRuns.meta.chapterRuns.ch02.length,2);assert.equal(scoreRuns.meta.chapterRecords.ch02.firstRun.questionScore.correct,3);assert.equal(scoreRuns.meta.chapterRecords.ch02.latestRun.questionScore.correct,5);assert.equal(scoreRuns.meta.chapterRecords.ch02.bestQuestionScore,5);
const legacy=INITIAL();legacy.version=3;legacy.run.started=true;legacy.run.completed=true;legacy.run.storyId='complete';legacy.run.stats.wealth=30;legacy.meta.cards.push('legacy-card');delete legacy.run.currentChapter;delete legacy.meta.completedChapters;delete legacy.meta.chapterRecords;
const migrated=migrateSave(legacy);assert.equal(migrated.version,8);assert(migrated.meta.completedChapters.includes('ch01'));assert(migrated.meta.chapterRecords.ch01);assert.equal(migrated.meta.chapterRuns.ch01.length,1);assert.equal(migrated.run.stats.wealth,30);assert.equal(migrated.run.playerOutfit,'goryeo_commoner');assert.equal(migrated.run.flags.wearingModernClothes,false);assert(migrated.run.flags.hasModernClothes);
const midChapter=INITIAL();midChapter.version=4;midChapter.run.started=true;midChapter.run.storyId='village';const migratedMid=migrateSave(midChapter);assert.equal(migratedMid.run.playerOutfit,'goryeo_commoner');assert.equal(migratedMid.run.flags.wearingModernClothes,false);assert(migratedMid.run.inventory.some(item=>item.id==='modern-clothes'&&item.status==='stored'));assert(migratedMid.run.inventory.some(item=>item.id==='goryeo-commoner-clothes'&&item.status==='equipped'));
const pendingHouse=INITIAL();pendingHouse.version=4;pendingHouse.run.started=true;pendingHouse.run.storyId='village';pendingHouse.run.pending={sourceSceneId:'house',nextStoryId:'village'};const migratedPending=migrateSave(pendingHouse);assert.equal(migratedPending.run.storyId,'outfit_question');assert.equal(migratedPending.run.pending.nextStoryId,'outfit_question');assert.equal(migratedPending.run.flags.wearingModernClothes,true);
const earlyGiftV6=INITIAL();earlyGiftV6.version=6;earlyGiftV6.run.started=true;earlyGiftV6.run.storyId='outfit_gift';earlyGiftV6.run.dialogueCursor=3;earlyGiftV6.run.flags.wearingModernClothes=false;earlyGiftV6.run.flags.receivedGoryeoClothesFromDoyun=true;earlyGiftV6.run.inventory.push({id:'goryeo-commoner-clothes',status:'equipped',source:'doyun'});const repairedEarlyGift=migrateSave(earlyGiftV6);assert.equal(repairedEarlyGift.run.playerOutfit,'modern');assert.equal(repairedEarlyGift.run.flags.receivedGoryeoClothesFromDoyun,false);assert(!repairedEarlyGift.run.inventory.some(item=>item.id==='goryeo-commoner-clothes'));
const brokenV6=INITIAL();brokenV6.version=6;brokenV6.run.started=true;brokenV6.run.storyId='village';brokenV6.run.playerOutfit='modern';brokenV6.run.flags.wearingModernClothes=true;const repairedV6=migrateSave(brokenV6);assert.equal(repairedV6.run.playerOutfit,'goryeo_commoner');assert.equal(repairedV6.run.flags.wearingModernClothes,false);
const replayV6=INITIAL();replayV6.version=6;replayV6.meta.completedChapters.push('ch01');replayV6.run.started=true;replayV6.run.mode='replay';replayV6.run.replayChapterId='ch01';replayV6.run.storyId='prologue';const repairedReplay=migrateSave(replayV6);assert.equal(repairedReplay.run.playerOutfit,'modern');assert.equal(repairedReplay.run.flags.wearingModernClothes,true);
const mysterySave=INITIAL();mysterySave.version=5;mysterySave.run.started=true;mysterySave.run.currentChapter='ch02';mysterySave.run.storyId='ch02_reflection';mysterySave.run.sharedEvents.push('noticed_unchanged_appearance');mysterySave.meta.mysteries.push('unknown-aging');mysterySave.meta.knowledgeMemory['unknown-aging']={title:'???'};const migratedMystery=migrateSave(mysterySave);assert.equal(migratedMystery.run.storyId,'ch02_purge');assert(!migratedMystery.run.sharedEvents.includes('noticed_unchanged_appearance'));assert(!migratedMystery.meta.mysteries.includes('unknown-aging'));assert(!migratedMystery.meta.knowledgeMemory['unknown-aging']);
const currentMystery=INITIAL();currentMystery.run.started=true;currentMystery.run.currentChapter='ch02';currentMystery.run.storyId='ch02_mystery';applySceneEntry(currentMystery,'ch02_mystery');const migratedCurrentMystery=migrateSave(currentMystery);assert(migratedCurrentMystery.meta.mysteries.includes('unknown-aging'));assert(migratedCurrentMystery.meta.knowledgeMemory['unknown-aging']);assert(migratedCurrentMystery.run.sharedEvents.includes('noticed_unchanged_appearance'));
const manifest=fs.readFileSync('docs/CHARACTER_ASSET_REQUIRED.md','utf8');for(const id of Object.keys(PORTRAITS))assert(manifest.includes('`'+id+'`'),`portrait manifest missing ${id}`);
console.log(JSON.stringify({scenes:Object.keys(STORIES).length,ch01Scenes:Object.values(STORIES).filter(s=>s.chapterId==='ch01').length,ch02Scenes:Object.values(STORIES).filter(s=>s.chapterId==='ch02').length,questions:QUESTIONS.length,ch02Paths:ch2Coverage.paths,ch02Choices:ch2Coverage.choices.size,status:'PASS'}));
